version: '3.8'

services:
  outpost:
    image: outpost:latest
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  seaweedfs:
    image: seaweedfs/seaweedfs:latest
    ports:
      - 8077:8077
      - 8078:8078
    volumes:
      - outpost-data:/data


volumes:
  outpost-data:
    driver: local
